name: CI

on:
    push:
        branches: [master]
    pull_request:

# Make sure CI fails on all warnings, including Clippy lints
env:
    RUSTFLAGS: "-Dwarnings"

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run Clippy
              run: |
                  cargo clippy --all-targets --all-features -- \
                  -D clippy::correctness \
                  -D clippy::suspicious \
                  -D clippy::style \
                  -D clippy::complexity \
                  -D clippy::perf \
                  -D clippy::pedantic \
                  -D clippy::nursery

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run tests
              run: cargo test
